import { useMemo } from "react";
import { Link, useLocation } from "wouter";
import { ArrowLeft, CalendarDays, Check, LogIn, RefreshCw, X } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

export default function Admin() {
  const [, navigate] = useLocation();
  const { user, loading } = useAuth();
  const bookings = trpc.booking.adminList.useQuery(undefined, { enabled: user?.role === "admin" });
  const updateStatus = trpc.booking.adminUpdateStatus.useMutation({ onSuccess: () => { bookings.refetch(); toast.success("Booking updated"); } });
  const todayCount = useMemo(() => bookings.data?.filter(item => new Date(item.booking.startAt).toDateString() === new Date().toDateString()).length || 0, [bookings.data]);
  if (loading) return <div className="admin-loading">Loading workspace…</div>;
  if (!user) return <div className="admin-gate"><div className="admin-gate-card"><span className="brand-mark">+</span><h1>Owner workspace</h1><p>Sign in with the owner account to manage your bookings, working hours and customer details.</p><button className="primary-button" onClick={() => startLogin()}><LogIn size={16} /> Sign in</button><Link href="/">Back to website</Link></div></div>;
  if (user.role !== "admin") return <div className="admin-gate"><div className="admin-gate-card"><span className="brand-mark">!</span><h1>Access restricted</h1><p>This workspace is only available to the business owner.</p><Link href="/">Back to website</Link></div></div>;
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="/"><img src="/manus-storage/take-more-logo_88d6d8ae.png" alt="Take More — Retail & Web, Made Smarter" /></a><p className="eyebrow">OWNER WORKSPACE</p><nav><a className="active"><CalendarDays size={17} /> Bookings</a><a><RefreshCw size={17} /> Availability <small>soon</small></a></nav><Link className="back-site" href="/"><ArrowLeft size={16} /> Back to website</Link></aside><main className="admin-main"><div className="admin-heading"><div><p className="eyebrow">BOOKING CONTROL</p><h1>Good to see you, {user.name?.split(" ")[0] || "owner"}.</h1><p>Manage real-time appointments and keep every conversation moving.</p></div><button className="refresh-button" onClick={() => bookings.refetch()}><RefreshCw size={15} /> Refresh</button></div><div className="admin-metrics"><div><span>Total bookings</span><strong>{bookings.data?.length || 0}</strong></div><div><span>Today</span><strong>{todayCount}</strong></div><div><span>Confirmed</span><strong>{bookings.data?.filter(item => item.booking.status === "confirmed").length || 0}</strong></div></div><section className="booking-table-card"><div className="table-title"><h2>Recent bookings</h2><span>Live availability protected</span></div>{bookings.isLoading ? <p className="muted">Loading bookings…</p> : bookings.data?.length ? <div className="booking-table"><div className="table-row table-head"><span>Customer</span><span>Service</span><span>Date & time</span><span>Status</span><span /></div>{bookings.data.map(({ booking, service }) => <div className="table-row" key={booking.id}><span><strong>{booking.customerName}</strong><small>{booking.customerPhone}</small></span><span>{service?.name || "Service"}</span><span>{new Date(booking.startAt).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Cairo" })}</span><span><b className={`status ${booking.status}`}>{booking.status}</b><small>{booking.bookingCode}</small></span><span className="row-actions">{booking.status === "confirmed" ? <button title="Cancel" onClick={() => updateStatus.mutate({ id: booking.id, status: "cancelled" })}><X size={15} /></button> : <button title="Confirm" onClick={() => updateStatus.mutate({ id: booking.id, status: "confirmed" })}><Check size={15} /></button>}</span></div>)}</div> : <div className="empty-state"><CalendarDays size={25} /><h3>No bookings yet</h3><p>New appointments will appear here instantly.</p></div>}</section></main></div>;
}
